export const partier2019 = [
    "Alliansen",
    "Arbeiderpartiet",
    "Demokratene",
    "Feministisk Initiativ",
    "Folkeaksjonen Nei til mer bompenger",
    "Fremskrittspartiet",
    "Helsepartiet",
    "Høyre",
    "Kristelig Folkeparti",
    "Kystpartiet",
    "Liberalistene",
    "Miljøpartiet De Grønne",
    "Norges Kommunistiske Parti",
    "Partiet De Kristne",
    "Pensjonistpartiet",
    "Piratpartiet",
    "Rødt",
    "Selvstendighetspartiet",
    "Senterpartiet",
    "SV – Sosialistisk Venstreparti",
    "Venstre"
]

export const partier2023 = [
    "Alliansen - Alternativ for Norge",
    "Arbeiderpartiet",
    "Folkestyret-listen",
    "Folkets Parti",
    "Fremskrittspartiet",
    "Høyre",
    "Industri- og Næringspartiet",
    "Konservativt",
    "Kristelig Folkeparti",
    "Kystpartiet",
    "Liberalistene",
    "Miljøpartiet De Grønne",
    "Norgesdemokratene",
    "Norges Kommunistiske Parti",
    "Partiet Mot Bompenger",
    "Partiet Sentrum",
    "Pensjonistpartiet",
    "Rødt",
    "Senterpartiet",
    "SV - Sosialistisk Venstreparti",
    "Venstre"
]
